package models;
// Generated Jun 17, 2022 1:09:03 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ArticlesApprovisionnement generated by hbm2java
 */
@Entity
@Table(name = "articles_approvisionnement", catalog = "stock")
public class ArticlesApprovisionnement implements java.io.Serializable {

	private int codeArt;
	private int qteCommande;
	private String datePrevueLivraison;

	public ArticlesApprovisionnement() {
	}

	public ArticlesApprovisionnement(int codeArt, int qteCommande, String datePrevueLivraison) {
		this.codeArt = codeArt;
		this.qteCommande = qteCommande;
		this.datePrevueLivraison = datePrevueLivraison;
	}

	@Id

	@Column(name = "codeArt", unique = true, nullable = false)
	public int getCodeArt() {
		return this.codeArt;
	}

	public void setCodeArt(int codeArt) {
		this.codeArt = codeArt;
	}

	@Column(name = "qteCommande", nullable = false)
	public int getQteCommande() {
		return this.qteCommande;
	}

	public void setQteCommande(int qteCommande) {
		this.qteCommande = qteCommande;
	}

	@Column(name = "datePrevueLivraison", nullable = false, length = 20)
	public String getDatePrevueLivraison() {
		return this.datePrevueLivraison;
	}

	public void setDatePrevueLivraison(String datePrevueLivraison) {
		this.datePrevueLivraison = datePrevueLivraison;
	}

}
